# Generated by Django 5.1.4 on 2025-01-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
